added email whitelist
Murrengan/murr_front pull request #55
Opened 2020-09-09 16:47 UTC by Murrengan

2020-09-09 16:55 UTC, DemonOFmooN requested changes

2020-09-09 16:55 UTC, DemonOFmooN commented on src/components/murren/SignUp.vue
> +import { whitelistEmails } from "./whitelistEmails";
Лучше зашить в `vuex` чтобы в дальнейшем можно было тянуть список с бека для расширяемости списка.

2020-09-10 09:08 UTC, Murrengan commented on src/components/murren/SignUp.vue
> +import { whitelistEmails } from "./whitelistEmails";
Думаешь, это хорошая идея?

2020-09-10 13:22 UTC, DemonOFmooN commented on src/components/murren/SignUp.vue
> +import { whitelistEmails } from "./whitelistEmails";
Для дальнейшего масштабирования нужно, вот луче сделать это через vuex что бы потом можно было реализовать api endpoint для получения списка почтовиков которые входят в белый список и этот список нужно в базе хранить что бы был легкий менеджмент. 

А так харкодить это в самом JS не масштабируемое и для внесения изменений нужно будет ребилдить каждый раз фронд для ребилда нужно будет каждый раз менять master brach. Очень много телодвижений надо будет делать.

2020-09-10 13:28 UTC, Murrengan commented on src/components/murren/SignUp.vue
> +import { whitelistEmails } from "./whitelistEmails";
а с технической стороны - это защитит от регистрации через левые почты?

2020-09-10 13:29 UTC, DemonOFmooN commented on src/components/murren/SignUp.vue
> +import { whitelistEmails } from "./whitelistEmails";
на стороне фронда да но на стороне бека это еще не реализовано.

2020-09-10 13:34 UTC, Murrengan commented on src/components/murren/SignUp.vue
> +import { whitelistEmails } from "./whitelistEmails";
на беке не смогут регаться без рекапчи

2020-09-10 13:48 UTC, DemonOFmooN commented on src/components/murren/SignUp.vue
> +import { whitelistEmails } from "./whitelistEmails";
Валидация нужна на беке, оставлять ее на усмотрения фронда мы не может, так как  обойти капчу возможно через платные сервисы.

2020-09-10 14:02 UTC, Murrengan commented on src/components/murren/SignUp.vue
> +import { whitelistEmails } from "./whitelistEmails";
На беке таска висит

2020-09-10 14:06 UTC, DemonOFmooN commented on src/components/murren/SignUp.vue
> +import { whitelistEmails } from "./whitelistEmails";
Ну да, таск есть но он как раз только для бека, https://trello.com/c/q1UrdcNC для фронда я таск не вижу.

2020-09-10 17:28 UTC, merged